### ISSUE TITLE
tag2pix_512.pkl dump only contains an integer

### ISSUE THREAD

**Issue by hliu549** [MerHS/tag2pix-gui#2]
Hi, as I am trying to use the GUI, I encountered the following error:

Traceback (most recent call last):
  File "Tag2Pix-release/main.py", line 117, in <module>
    main()
  File "Tag2Pix-release/main.py", line 106, in main
    gan = tag2pix(args)
  File "/home/ec2-user/tag2pix-gui/Tag2Pix-release/tag2pix.py", line 61, in __init__
    self.iv_dict, self.cv_dict, self.id_to_name = get_tag_dict(args.tag_dump)
  File "/home/ec2-user/tag2pix-gui/Tag2Pix-release/loader/dataloader.py", line 38, in get_tag_dict
    iv_tag_list = pkl['iv_tag_list']
TypeError: 'int' object is not subscriptable

And I found that the downloaded tag2pix_512.pkl dump only returns an integer 119547037146038801333356 when doing the following unpickling:

with open('tag2pix_512.pkl', 'rb') as f:
     pkl = pickle.load(f)

However, the downloaded file tag2pix_512.pkl does show taking 71MB spaces. Wondering what is going on here. Thanks in advance.

**Comment by MerHS** [comment]
`tag2pix_512.pkl` is a PyTorch network dump, therfore you cannot load it with `pickle.load`. (it requires `torch.load`)

The script you ran is not the GUI code. That's a training code from `https://github.com/blandocs/Tag2Pix`

To test the GUI version, please clone this code repository with `git clone https://github.com/MerHS/tag2pix-gui` and run `tag2pix-guit/main.py`.
